// setCurrentUserOnline
export const SET_USER_ONLINE = 'SET_USER_ONLINE';
export const SET_USER_ONLINE_SUCCESS = 'SET_USER_ONLINE_SUCCESS';
export const SET_USER_ONLINE_FAILURE = 'SET_USER_ONLINE_FAILURE';
// fetchOnlineUsers
export const FETCH_ONLINE_USERS = 'FETCH_ONLINE_USERS';
export const FETCH_ONLINE_USERS_SUCCESS = 'FETCH_ONLINE_USERS_SUCCESS';
export const FETCH_ONLINE_USERS_FAILURE = 'FETCH_ONLINE_USERS_FAILURE';
// getUsers
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';